name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Taskfile
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin/task
          task --version

      - name: Build Docker Image
        run: task build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Taskfile
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin/task
          task --version

      - name: Linters
        run: task lint