name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Taskfile
        uses: ./.github/actions/taskfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: task build

      - name: Save Docker image as artifact
        run: |
          docker save $IMAGE_NAME:$IMAGE_TAG | gzip > image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Taskfile
        uses: ./.github/actions/taskfile

      - name: Linters
        run: task lint

  trigger-push-docker-image:
    needs: [ build, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: push-docker-image
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }