name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Taskfile
        uses: ./.github/workflows/install-task.yml

      - name: Build Docker Image
        run: task build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Taskfile
        uses: ./.github/workflows/install-task.yml

      - name: Linters
        run: task lint