name: cicd

on:
  - push

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Taskfile
        uses: ./.github/actions/taskfile

      - name: Linters
        run: task lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Taskfile
        uses: ./.github/actions/taskfile

      - name: Set Up Docker Sdk
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: task build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tags (main)
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/crypto-positions-manager"
          IMAGE_TAG="main-${GITHUB_SHA::7}"
          LATEST_TAG="latest"

      - name: Determine Docker tags (other branches)
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SAFE_BRANCH=${BRANCH_NAME//\//-}
          
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/crypto-positions-manager"
          IMAGE_TAG="${SAFE_BRANCH}-${GITHUB_SHA::7}"
          LATEST_TAG="${SAFE_BRANCH}-latest"

      - name: Build and Push Docker images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -t $IMAGE_NAME:$LATEST_TAG \
            -f build/Dockerfile \
            --push .
