name: push-docker-image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit to deploy'
        required: true
        default: 'main'
      sha:
        description: 'Commit SHA'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}